apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-service
  namespace: operion-sandbox

spec:
  replicas: 1

  selector:
    matchLabels:
      app: payment-service
  
  template:
    metadata:
      labels:
        app: payment-service

    spec:
      containers:
        - name: payment-service
          image: operion-payment-service:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000
