apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: operion-sandbox
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: operion-payment-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PAYMENT_PROVIDER_URL
              value: "http://payment-provider.local"
            - name: INCIDENT_MODE
              value: "oom"
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
